server:
  port: ${PORT:8081}
  forward-headers-strategy: native
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/sulabh}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${JWT_EXPIRATION:86400000}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:*}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization
  allow-credentials: true
  max-age: 3600

storage:
  base-dir: ./uploads

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
