server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sulabh
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: change_this_local_secret
  expirationMs: 86400000

storage:
  base-dir: ./uploads

frontend:
  url: http://localhost:5173
